package similaritycalculation.gst;

public enum TokenValue {
	CUSTOM_STRING, AT, INTERFACE, OPENING_BRACKET, SEMICOLON, CLOSING_BRACKET, OPENING_PARENTHESIS, 
	CLOSING_PARENTHESIS, DEFAULT, OPENING_SQUARE_BRACKET, CLOSING_SQUARE_BRACKET, NEW, COMMA, ASSERT, 
	COLON, BREAK, CATCH, LESS_THAN, DOT, GREATER_THAN, INTERROGATION_MARK, THIS, CONTINUE, DOUBLE_COLON, 
	EMPTY_SQUARE_BRACKETS, DO, WHILE, FOR, ENUM, IMPLEMENTS, IF, ELSE, IMPORT, STATIC, DOT_ASTERISK, 
	INSTANCEOF, AMPERSAND, ARROW, HASH, EQUAL, THREE_DOTS, VOID, THROWS, PACKAGE, RETURN, SUPER, CASE, 
	SWITCH, SYNCHRONIZED, THROW, TRY, FINALLY, CLASS, EXTENDS, VERTICAL_BAR, FIELD_NAME, PARAMETER_NAME, 
	ENUM_CONSTANT_NAME, VARIABLE_NAME, INTERFACE_DECLARATION, CLASS_DECLARATION, MODEL_CLASS_NAME, 
	MODEL_FIELD_NAME, MODEL_CLASS_METHOD_INVOCATION, TYPE, VARIABLE_DECLARATION, CLASS_INSTANCE_CREATION, 
	METHOD_INVOCATION
}
