/*
 * Copyright (c) 2013 RWTH Aachen. All rights reserved.
 *
 * http://www.se-rwth.de/
 */
package similaritycalculation.gst.asttokenizer;

/**
 * Abstract representation of a part of a java class. In this way, a java class can be represented
 * by a number of abstract symbols which indicate the syntactical structure of the java class.
 * 
 * @author (last commit) $Author$
 * @version $Revision$, $Date$
 */
public enum TokenSymbols_Step10 {
  IMPORT_DECLARATION, CLASS_DECLARATION, INTERFACE_DECLARATION, VARIABLE_DECLARATION,
  METHOD_DECLARATION, STATIC_INITIALIZATION, CONSTRUCTOR_DECLARATION, CONSTRUCTOR_INVOCATION_THIS,
  CONSTRUCTOR_INVOCATION_SUPER, CONSTANT_DECLARATION, ABSTRACT_METHOD_DECLARATION, SWITCH, BREAK,
  CONTINUE, RETURN, SYNCHRONIZED, THROW, TRY, ASSERT, ASSIGNMENT, METHOD_INVOCATION, NEW, BLOCK,
  CATCH, FINALLY, CASE, ELSE, IF, DO, INNER_CLASS_DECLARATION, INNER_INTERFACE_DECLARATION,
  INNER_CLASS_DECLARATION_END, INNER_INTERFACE_DECLARATION_END, CLASS_DECLARATION_END,
  INTERFACE_DECLARATION_END, METHOD_DECLARATION_END, CONSTRUCTOR_DECLARATION_END, SYNCHRONIZED_END,
  DO_END, WHILE_END, SWITCH_END, WHILE, BLOCK_END, FOR, FOR_END, CATCH_END, FINALLY_END, TRY_END,
  PACKAGE_DECLARATION, ANONYMOUS_INNER_CLASS, ANONYMOUS_INNER_CLASS_END, IF_END, ELSE_END,
  ENUM_DECLARATION, ENUM_DECLARATION_END, INNER_ENUM_DECLARATION, INNER_ENUM_DECLARATION_END;
}
